import type { WorldSpec } from './types'

/**
 * Small, keyless planner fixture for deterministic smoke tests. It exercises
 * terrain masks, rivers, and placement rules without making a remote API call;
 * it is not a production mesh source.
 */
export const DEMO_SPEC: WorldSpec = {
  name: 'Emberfall Reach',
  logline: 'A frostbitten river valley between ridge and dune, watched by standing stones and a lonely keep.',
  seed: 20260810,
  size: 280,
  seaLevel: 0,
  sky: {
    panoramaPrompt: 'vast cold evening sky over a mountain river valley, low golden sun breaking through broken clouds, distant snowy ridgelines on the horizon',
    sunAzimuth: 235,
    sunElevation: 22,
    sunColor: '#ffd9a0',
    sunIntensity: 2.4,
    ambientColor: '#a7bccf',
    ambientIntensity: 0.5,
    fogColor: '#c2cfd8',
    fogDensity: 0.28,
  },
  regions: [
    {
      id: 'north-ridge',
      name: 'North Ridge',
      kind: 'mountain',
      center: [0.5, 0.16],
      radius: 0.34,
      irregularity: 0.6,
      baseElevation: 12,
      amplitude: 45,
      roughness: 0.75,
      material: {
        name: 'granite scree',
        texturePrompt: 'seamless tileable texture, gray granite scree with lichen, top-down, photorealistic, even diffuse lighting',
        color: '#8a877c',
        tiling: 6,
      },
    },
    {
      id: 'vale',
      name: 'The Vale',
      kind: 'plains',
      center: [0.46, 0.55],
      radius: 0.3,
      irregularity: 0.55,
      baseElevation: 2,
      amplitude: 4,
      roughness: 0.35,
      material: {
        name: 'frost meadow',
        texturePrompt: 'seamless tileable texture, frost-dusted meadow grass, top-down, photorealistic, even diffuse lighting',
        color: '#7d9457',
        tiling: 6,
      },
    },
    {
      id: 'east-forest',
      name: 'Whisperwood',
      kind: 'forest',
      center: [0.76, 0.48],
      radius: 0.2,
      irregularity: 0.7,
      baseElevation: 4,
      amplitude: 8,
      roughness: 0.5,
      material: {
        name: 'forest floor',
        texturePrompt: 'seamless tileable texture, dark forest floor with pine needles and moss, top-down, photorealistic',
        color: '#4c6b3c',
        tiling: 6,
      },
    },
    {
      id: 'south-dunes',
      name: 'Ashen Dunes',
      kind: 'dunes',
      center: [0.3, 0.84],
      radius: 0.22,
      irregularity: 0.45,
      baseElevation: 2,
      amplitude: 8,
      roughness: 0.4,
      material: {
        name: 'pale sand',
        texturePrompt: 'seamless tileable texture, pale wind-rippled sand, top-down, photorealistic, even diffuse lighting',
        color: '#cdb586',
        tiling: 6,
      },
    },
    {
      id: 'mirror-lake',
      name: 'Mirror Lake',
      kind: 'water',
      center: [0.72, 0.8],
      radius: 0.16,
      irregularity: 0.5,
      baseElevation: -5,
      amplitude: 6,
      roughness: 0.2,
      material: {
        name: 'lakebed pebbles',
        texturePrompt: 'seamless tileable texture, wet dark lakebed pebbles, top-down, photorealistic',
        color: '#39597a',
        tiling: 6,
      },
    },
  ],
  rivers: [
    {
      id: 'ember-run',
      path: [[0.5, 0.12], [0.47, 0.4], [0.55, 0.62], [0.68, 0.78]],
      width: 10,
      depth: 3,
    },
  ],
  assets: [
    {
      id: 'keep',
      name: 'Lonely Keep',
      category: 'structure',
      imagePrompt: 'isometric game asset, weathered stone keep with a single tower and snow on the battlements',
      targetHeight: 22,
      tier: 'hero',
      proceduralHint: 'hut',
      placements: [
        { regions: ['vale'], count: 1, arrangement: 'cluster', anchor: [0.42, 0.46], spacing: 30, maxSlope: 16, scaleJitter: 0, faceAlong: false },
      ],
    },
    {
      id: 'hamlet-house',
      name: 'Riverside Cottage',
      category: 'structure',
      imagePrompt: 'isometric game asset, small timber-and-stone cottage with snowy thatched roof',
      targetHeight: 5.5,
      tier: 'hero',
      proceduralHint: 'hut',
      placements: [
        { regions: ['vale'], count: 8, arrangement: 'waterfront', spacing: 8, maxSlope: 14, scaleJitter: 0.1, faceAlong: true },
      ],
    },
    {
      id: 'standing-stone',
      name: 'Standing Stone',
      category: 'prop',
      imagePrompt: 'isometric game asset, tall runic standing stone monolith, weathered granite',
      targetHeight: 6,
      tier: 'hero',
      proceduralHint: 'monolith',
      placements: [
        { regions: ['south-dunes'], count: 6, arrangement: 'ring', spacing: 10, maxSlope: 25, scaleJitter: 0.15, faceAlong: true },
      ],
    },
    {
      id: 'pine',
      name: 'Frost Pine',
      category: 'vegetation',
      imagePrompt: 'isometric game asset, snow-dusted pine tree',
      targetHeight: 11,
      tier: 'scatter',
      proceduralHint: 'pine',
      placements: [
        { regions: ['east-forest'], count: 120, arrangement: 'scatter', spacing: 5, maxSlope: 32, scaleJitter: 0.35, faceAlong: false },
        { regions: ['north-ridge'], count: 40, arrangement: 'scatter', spacing: 7, maxSlope: 30, scaleJitter: 0.35, faceAlong: false },
      ],
    },
    {
      id: 'boulder',
      name: 'Glacial Boulder',
      category: 'rock',
      imagePrompt: 'isometric game asset, mossy glacial boulder',
      targetHeight: 2.4,
      tier: 'scatter',
      proceduralHint: 'boulder',
      placements: [
        { regions: ['north-ridge'], count: 30, arrangement: 'scatter', spacing: 6, maxSlope: 45, scaleJitter: 0.4, faceAlong: false },
        { regions: ['vale'], count: 12, arrangement: 'scatter', spacing: 9, maxSlope: 40, scaleJitter: 0.4, faceAlong: false },
      ],
    },
    {
      id: 'grass-tuft',
      name: 'Meadow Tuft',
      category: 'vegetation',
      imagePrompt: 'isometric game asset, tuft of meadow grass',
      targetHeight: 0.8,
      tier: 'scatter',
      proceduralHint: 'grass',
      placements: [
        { regions: ['vale'], count: 180, arrangement: 'scatter', spacing: 2.5, maxSlope: 30, scaleJitter: 0.35, faceAlong: false },
      ],
    },
    {
      id: 'ice-crystal',
      name: 'Ice Crystal',
      category: 'rock',
      imagePrompt: 'isometric game asset, glowing blue ice crystal cluster',
      targetHeight: 1.8,
      tier: 'scatter',
      proceduralHint: 'crystal',
      placements: [
        { regions: ['north-ridge'], count: 14, arrangement: 'scatter', spacing: 8, maxSlope: 38, scaleJitter: 0.4, faceAlong: false },
      ],
    },
  ],
  relations: [
    { subject: 'hamlet-house', relation: 'near', object: 'ember-run' },
    { subject: 'keep', relation: 'overlooking', object: 'vale' },
  ],
}
