import { create } from 'zustand'
import { buildTerrain, type BuiltTerrain } from './runtime/terrain'
import { solvePlacements } from './runtime/placement'
import { isRenderableWorldSpec, type Instance } from './runtime/types'
import type { WorldDocument } from './types'

export interface WorldState {
  document: WorldDocument | null
  terrain: BuiltTerrain | null
  instances: Instance[]
  selectedProtoId: string | null
  saving: boolean
  error: string | null
  setSelectedProtoId: (protoId: string | null) => void
  replaceDocument: (document: WorldDocument) => void
  save: () => Promise<void>
  clearError: () => void
}

function now(): string {
  return new Date().toISOString()
}

function prepare(document: WorldDocument): { document: WorldDocument; terrain: BuiltTerrain | null; instances: Instance[] } {
  const environment = document.runtime.build.environment
  if (!isRenderableWorldSpec(environment)) {
    return { document, terrain: null, instances: [] }
  }

  // Terrain samples are used only to solve deterministic semantic positions;
  // production geometry is generated by Blender and attached as a workspace
  // artifact. The WorldCanvas never converts these samples into a mesh.
  const terrain = buildTerrain(environment, { resolution: 96 })
  const configured = document.runtime.compiled.instances
  const instances = configured.length > 0 ? configured : solvePlacements(environment, terrain)
  if (configured.length > 0) return { document, terrain, instances }

  return {
    document: {
      ...document,
      runtime: {
        ...document.runtime,
        compiled: { ...document.runtime.compiled, instances },
      },
    },
    terrain,
    instances,
  }
}

export const useWorldStore = create<WorldState>((set, get) => ({
  document: null,
  terrain: null,
  instances: [],
  selectedProtoId: null,
  saving: false,
  error: null,

  setSelectedProtoId: (selectedProtoId) => set({ selectedProtoId }),
  replaceDocument: (document) => {
    const next = prepare(document)
    set({ ...next, error: null, selectedProtoId: null })
  },
  async save() {
    const current = get().document
    if (!current) return
    const { saveWorld } = await import('./worldApi')
    set({ saving: true, error: null })
    try {
      const document = { ...current, updated_at: now() }
      await saveWorld(document)
      set({ document, saving: false })
    } catch (error) {
      set({ saving: false, error: error instanceof Error ? error.message : String(error) })
    }
  },
  clearError: () => set({ error: null }),
}))
